# Generated by Django 6.0.4 on 2026-04-28 05:13

from django.core.files.storage import FileSystemStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=FileSystemStorage(), upload_to='userprofile/'),
        ),
    ]
